### ISSUE TITLE
Simulating Lensing Signals in Galaxy Clusters using cosmoDC2 for LSST

### ISSUE THREAD

**Issue by linan7788626** [linan7788626/HackDays#3]
## Motivations
*Many thanks to Graham (@mahargthims)*

The WFD survey will in principle yield thousands of cluster strong lenses that can be used for a broad range of science within DESC, SLSC, Galaxies SC, and TVSSC. For example, within DESC, strong lensing cluster cores will contribute to several aspects of CLWG activities including blending issues as a function of cluster-centric radius, and providing a project mass anchor against which to compare weak-lensing halo masses. Given the technique-focused nature of strong lens finding/modelling (at any mass scale), the natural home for this work is within the SLSC/DESC-SLWG community, whilst collaborating closely with colleagues in other WGs and SCs.

As a first step to developing/testing cluster strong lens finding algorithms on DC2 data, this hack aims to produce a DC2-based observation of a single strong lensing cluster. We anticipate expanding this pilot study to create a large suite of DC2 cluster strong lenses that can be used both to test lens finding algorithms and to devise tests of DC2.

The pilot study is deliberately simple in its approach. It chooses a cluster from DC2 (MFOF=7E14Msun/h), models this as an NFW halo, and adds cluster galaxies as perturbers based on truncated SIE profiles located at the position of galaxies within the DC2 catalogue. The mass assigned to these galaxies is calculated using scaling relations based on well-established lens modeling techniques, and is subtracted from the cluster scale mass component in order to conserve mass. The background galaxies are ray traced through the mass distribution to produce a 3x3arcmin field of view colour image. The two colour images below are before (upper) and after (lower) ray tracing.

## Products

- ***IDEAL CASE***
The two images below are in r-band only. This is a demonstration for the comparison between a cluster light cone with and without gravitational lensing. 

No Lensing           | With Lensing
:-------------------------:|:-------------------------:
 ![No Lensing](https://user-images.githubusercontent.com/1016652/61533019-e8f1ff00-aa2b-11e9-9668-0fb673cdcaf8.png) |  ![With Lensing](https://user-images.githubusercontent.com/1016652/61533021-eb545900-aa2b-11e9-9063-05333537b6ca.png)

- ***With Simple PSF and Noise Models***

The arcs showed above are too faint to be observed in the noisy images. Therefore, we put a source around the caustics (higher magnification region) of the cluster lens.

No Lensing           | With Lensing
:-------------------------:|:-------------------------:
 ![download-2](https://user-images.githubusercontent.com/1016652/61539565-147ce580-aa3c-11e9-91ce-0f213ed2fb55.png) |  ![download-3](https://user-images.githubusercontent.com/1016652/61539572-18106c80-aa3c-11e9-8586-aebb007bae35.png)

## To-do List
- [ ] More realistic M200 and Concentration, DC2 addon-catalog?
- [x] More realistic mass models for member galaxies, Jaffe.
- [x] More sufficient way to extract light cones from DC2 with [GCR](https://github.com/LSSTDESC/gcr-catalogs). 
- [ ] Larger sample of sims for training cluster-scale lens-finders
- [x] Larger field of view to include weak lensing. 

## References
1. https://arxiv.org/abs/1511.03673
2. https://arxiv.org/abs/1907.06530 
3. https://arxiv.org/abs/1905.13236

**Comment by mahargpsmith** [comment]
The WFD survey will in principle yield thousands of cluster strong lenses that can be used for a broad range of science within DESC, SLSC, Galaxies SC, and TVSSC.  For example, within DESC, strong lensing cluster cores will contribute to several aspects of CLWG activities including blending issues as a function of cluster-centric radius, and providing a project mass anchor against which to compare weak-lensing halo masses.   Given the technique-focused nature of strong lens finding/modelling (at any mass scale), the natural home for this work is within the SLSC/DESC-SLWG community, whilst collaborating closely with colleagues in other WGs and SCs.  

As a first step to developing/testing cluster strong lens finding algorithms on DC2 data, this hack aims to produce a DC2-based observation of a single strong lensing cluster. We anticipate expanding this pilot study to create a large suite of DC2 cluster strong lenses that can be used both to test lens finding algorithms and to devise tests of DC2.  

The pilot study is deliberately simple in its approach.  It chooses a cluster from DC2 (M200=7E14Msun), models this as a NFW halo, and adds cluster galaxies as perturbers based on truncated SIE profiles located at the position of galaxies within the DC2 catalogue.  The mass assigned to these galaxies is calculated using scaling relations based on well-established lens modeling techniques, and is subtracted from the cluster scale mass component in order to conserve mass.  The background galaxies are ray traced through the mass distribution to produce a 3x3arcmin field of view colour image.  The two colour images below are before (upper) and after (lower) ray tracing.
